services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=task_db
      - MONGO_INITDB_ROOT_USERNAME=task_user
      - MONGO_INITDB_ROOT_PASSWORD=tasks_password
    ports:
      - "27017:27017"
    networks:
      - task-network

networks:
  task-network:
    driver: bridge
